version: "3"
services:
  frontend:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=Jean9882
      - MYSQL_DATABASE=gerenciador_de_contas
      - MYSQL_PASSWORD=Jean9882
    volumes:
      - ./db:/var/lib/mysql