version: "3"
services:
  frontend:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/path/no/contêiner
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=9000
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    container_name: db
    volumes:
      - ./backend:/db
    environment:
      - MYSQL_ROOT_PASSWORD=Jean9882
      - MYSQL_DATABASE=gerenciador_de_contas
      - MYSQL_PASSWORD=Jean9882