version: '3'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
